### ISSUE TITLE
Twenty Twenty: Custom heading font not applied

### ISSUE THREAD

**Issue by kristarella** [Automattic/themes#2049]
## Steps to replicate

1. From a Premium site e.g., https://badaboomtest.wordpress.com/ set custom font for Headings in Customize > Fonts
2. Save changes and View Site

## Result

Site title will be changed, but headings within content are not.

![Screen Shot on 2020-05-20 at 17:24:40](https://user-images.githubusercontent.com/2031017/82417427-e08ca980-9abe-11ea-8fe3-f080e686cd47.png)

## Expected

All headings should change.

## More info

This seems to be because of the CSS in style.css lines 3540-3571. Selectors such as `.entry-content h1` are not more specific than `.wf-active h1`. Jetpack custom fonts are being loaded earlier than theme CSS.

Maybe similar or related to #1795

* User report: #2981224-zd

**Comment by eduardozulian** [comment]
Another report in 22428933-hc

**Comment by AtrumGeost** [comment]
Another report here 22382056-hc

**Comment by allancole** [comment]
This is now fixed in 56485-wpcom-themes :-)

**Comment by eduardozulian** [comment]
@allancole can you confirm if these changes were pushed to WP.com AT sites as well? I am still seeing issues on version `1.4-wpcom`
