### ISSUE TITLE
Maywood and Balasana: Page Preview doesn't reflect color selections from Customizer

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/themes#2856]
The Colors & Backgrounds set in the Customizer are not reflected when you preview a page or post in Maywood and Balasana.

I also tested Seedlet, Mayland, and Alves and the issue does not happen with those themes.

## Steps to replicate

1. Activate Mayland theme
2. Change text color in the Colors & Backgrounds section of the Customizer to white, and change the background color to a darker color.
3. Go to the Pages page on the dashboard and click the three dots next to a post and select View Page.

## Result
The preview showed a white background with black text like this:

![image](https://user-images.githubusercontent.com/87168/103957081-98f08600-5152-11eb-979e-b64d2fb73f3f.png)

## Expected
I expected it to show a blue background with white text like this:

![image](https://user-images.githubusercontent.com/87168/103957090-9d1ca380-5152-11eb-85a7-db54d2b20dfe.png)

This also happened when using Balasana.

- Ticket: #3499991-zd

Possibly related to: https://github.com/Automattic/wp-calypso/issues/47117 and https://github.com/Automattic/themes/issues/2855

**Comment by scruffian** [comment]
I can't replicate this, I seems fine for me:
<img width="1428" alt="Screenshot 2020-12-02 at 14 06 49" src="https://user-images.githubusercontent.com/275961/100882971-b07b8580-34a7-11eb-9c5f-4def9b81c69f.png">

**Comment by ccwalburn** [comment]
I can't recreate the issue anymore either so it looks like it has been fixed.

**Comment by mriyazuddin** [comment]
Hey @scruffian looks like this issue is back. This time though it reflects the background color change for the menu only and not for entire page. I'm able to replicate this issue on a test site as well. Here's a video showing this: 

https://user-images.githubusercontent.com/49064126/168553013-d1a1ed50-02a0-44ea-b8f9-0d2be62913fb.mp4

User reported the issue here: #5216743-zd

**Comment by mriyazuddin** [comment]
I was able to replicate this issue on both simple and AT sites.
