### ISSUE TITLE
Twenty Twenty: Cover blocks aren't full width in the editor (but they are on the site)

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#3168]
## Steps to replicate
A user complained about this with their cover blocks. I was not able to replicate it at first unless I copied their source code.

But here's how we can see it certainly affects anyone using this theme:

- Enable Twenty Twenty
- Add a new page using a template that should have a full-width cover block

## Result
- Note the block does not appear to be full width in the editor
- If I publish the page, the block appears full width after all on the live site
- If _explicitly_ set the block to full width again, it's fine in both the editor and on the live site

![Screen Shot 2021-02-02 at 8 56 40 PM](https://user-images.githubusercontent.com/3476361/106696533-267c9580-659a-11eb-8586-c435ac545c59.png)

## Expected
- I'd expect full width blocks to appear full width in the editor, regardless of when I made the post or whether I used a template that should be full width

* User report: https://wordpress.com/forums/topic/all-cover-blocks-got-reset/
* Follow-up ticket: (Same)

**Comment by Columbo199X** [comment]
Hello I'm the user mentioned in the OP. I now went through all sites and posts and fixed the Cover Blocks. Everythings looking fine again except that the repeat background option doesn't work.

**Comment by supernovia** [comment]
> Hello I'm the user mentioned in the OP. I now went through all sites and posts and fixed the Cover Blocks. Everythings looking fine again except that the repeat background option doesn't work.

Thank you! I did notice if you explicitly set full width they should work. But, I can see it's also causing issues with our page templates, so it's still worth a look, IMO!

**Comment by Columbo199X** [comment]
Hey the previous issue with this block got fixed but about a week ago it came back. When I open a page or post in the block editor it's all squished together. Looking through it, it seems it's still the Cover Block that's causing the issue. If you place another Block on it like a Picture or Layout it is centered to the right regardles of what alignment you select.

**Comment by Columbo199X** [comment]
Hey just wanted to let you know that the problem has come back. All Cover blocks show up squished when I open a post or page in the editor eventhough their alignment is still set to full width.

**Comment by supernovia** [comment]
@Columbo199X  I'm sorry I missed this. Are you still having trouble?

**Comment by Columbo199X** [comment]
@supernovia Sorry for reporting back late. The previous issue was fixed. However since today there seems to be a different bug with the Cover block.
The transperency option doesn't seem to be working. Doesn't matter which value I set it to it still shows as 0%
[Screenshot](https://imgur.com/E2vu8vg)

**Comment by supernovia** [comment]
@Columbo199X  let's get the details ironed out in a support request so we can figure out whether we need to make a new issue here. Thanks in advance!

**Comment by jordesign** [comment]
It sounds as though this issue is resolved - user is now being effected by https://github.com/Automattic/wp-calypso/issues/57884

Closing this ticket for now.

**Comment by Columbo199X** [comment]
Hello. A few days ago this issue came back allthough now it's not just the cover block but the Layout/Columns Block are affected too.
Editor:
![Editor](https://user-images.githubusercontent.com/67553546/159485140-906e1203-52ee-49cd-9641-12d97b08a573.png)
Published:
![Screenshot 2022-03-22 at 13-42-54 Shonen Sonntag](https://user-images.githubusercontent.com/67553546/159485262-7c7dbde6-265b-40f3-9079-3c58c2daf2d2.png)

**Comment by KokkieH** [comment]
Discussing the Layout grid block issue in https://wordpress.com/forums/topic/twenty-twenty-alignment-of-blocks-reset-in-editor
