### ISSUE TITLE
Blank Canvas: custom color palettes not reflected in the editor

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#3316]
The editor does not reflect a custom color palette selection on wpcom:

<img width="2559" alt="Screen Shot 2021-02-19 at 11 06 21 AM" src="https://user-images.githubusercontent.com/5375500/108529632-aa28c880-72a2-11eb-93b4-28486da938ce.png">

Fixed:
- [x] Simple https://github.com/Automattic/themes/issues/3316#issuecomment-797467104
- [ ] Atomic

**Comment by simison** [comment]
@jffng @jeffikus any ETA for the fix? This is affecting .com flows quite a bit.

Customers see this in signup:

<img width="300" alt="Screenshot 2021-03-11 at 10 43 19" src="https://user-images.githubusercontent.com/87168/110759866-c216bb00-8256-11eb-864f-77ea6029e9a1.png">

<img width="600" alt="Screenshot 2021-03-11 at 10 43 41" src="https://user-images.githubusercontent.com/87168/110759880-c6db6f00-8256-11eb-950b-4fbd7bda5153.png">

...and then fall flat straight into the editor:

<img width="600" alt="Screenshot 2021-03-11 at 10 44 04" src="https://user-images.githubusercontent.com/87168/110759965-dfe42000-8256-11eb-9944-6eb3d03c5def.png">

This gives a pretty bad first impression and could affect churn.

cc @ianstewart

**Comment by jffng** [comment]
@simison thanks for the heads up, looking into this today.

**Comment by jffng** [comment]
It looks like this is broken for all themes because of an issue in the colors plugin itself. The editor style handle (`wp-editor-font`) that we attach the custom color variables has changed or been removed. Not sure why we were attaching it to an unrelated style handle in the first place, but there's a patch here:

D58563-code (h/t @jeffikus for the suggestion!)

Should also address https://github.com/Automattic/themes/issues/3153. 

@scruffian if this change works, how should I handle the changes to [github](https://github.com/Automattic/custom-colors)? Is github where atomic pulls from?

**Comment by scruffian** [comment]
I merged this on .com. 

It's more difficult on atomic because the plugin code is out of sync :(

**Comment by kjellr** [comment]
I'm still seeing this issue on Simple Sites when testing Blank Canvas patterns. I've selected one of the pre-made palettes in the Customizer, and it's not reflected at all in the editor. 

Editor: 

<img width="1163" alt="Screen Shot 2021-03-18 at 12 58 00 PM" src="https://user-images.githubusercontent.com/1202812/111665960-a0cf4500-87e9-11eb-9db7-9259d5c2cf71.png">

Front End:

<img width="1126" alt="Screen Shot 2021-03-18 at 12 58 13 PM" src="https://user-images.githubusercontent.com/1202812/111665956-a036ae80-87e9-11eb-9b95-666a74cc6281.png">

**Comment by simison** [comment]
@scruffian any news on the Atomic plugin version for this?

**Comment by scruffian** [comment]
I guess we should try to get a fix for the simple sites version before we look at Atomic.

**Comment by simison** [comment]
Oh, I thought the simple sites were fixed when you said "I merged this on .com." in https://github.com/Automattic/themes/issues/3316#issuecomment-797467104 , assuming "this" was D58563-code.

**Comment by scruffian** [comment]
Yeah that's what I thought at the time but then @kjellr found the issue above so there still seems to be an issue there. It's on our list to look at but it's a long list :)

**Comment by jffng** [comment]
I looked into this more closely and opened a fix for simple sites here: D59587-code

**Comment by simison** [comment]
@jffng can this now be closed? I saw D59701-code is deployed

**Comment by jffng** [comment]
We ended up needing to revert that last week because it created undesirable behavior in older themes. @MaggieCabrera and company are working on a revised approach, and we will keep this issue up-to-date.

**Comment by MaggieCabrera** [comment]
Yep, the new diff is D59960-code and it's being reviewed by @scruffian to see if it's a good candidate for a fix, else we still have this on our radar though

**Comment by jffng** [comment]
It looks like this issue is resolved on simple sites:

<img width="1279" alt="Screen Shot 2021-04-22 at 2 01 34 PM" src="https://user-images.githubusercontent.com/5375500/115764193-2189df80-a35a-11eb-9b70-90829664d0ed.png">

Atomic still does not reflect custom colors in the editor.

The issue of the editor color palette not reflecting the custom is separate and reported in https://github.com/Automattic/themes/issues/3614

**Comment by scruffian** [comment]
There's a fix for Atomic sites here: 24-gh-Automattic/custom-colors/files

**Comment by scruffian** [comment]
This should now be fixed on Atomic sites.
