### ISSUE TITLE
Dara: Images centered in Gutenberg display are aligned to the left

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/themes#376]
## Steps to replicate

1. Center an image with a caption in Gutenberg.
2. Preview or publish the page.

## Result

When you preview the page, the image appears aligned to the left with a very narrow caption: https://cld.wthms.co/UiQqTv

## Expected

The image should display aligned to center as it appears in the editor.

* User report: #7303077-hc
* Follow-up ticket: #1583213-zen

**Comment by laurelfulford** [comment]
Thanks for reporting this, @jamiepalatnik!

I can't quite reproduce this issue exactly as described - were you able to? This is what I've done:
1. Create an image block
2. Use a smaller image (which is what appears to be happening in the screenshot).
3. Add a caption.
4. Centre the block.

Both in the preview and in the published page, the image is left aligned (which needs to be fixed) but the caption is full-width:

![image](https://user-images.githubusercontent.com/177561/48862121-2f4a6d80-ed7a-11e8-9e32-d86b48e3cf86.png)

Just let. me know if I'm missing a step to get the narrow caption - thanks!

**Comment by laurelfulford** [comment]
I've deployed a fix that addresses the image not being centred in #377, and r51549-wpcom-themes. Once I can reproduce the caption issue, I can take care of that too!

**Comment by jamiepalatnik** [comment]
I'm still seeing the caption issue when I test. I tried:

1. Create an image block.
2. Use a smaller image.
3. Add a caption.
4. Center the block.

I also tried changing the order:

1. Create an image block.
2. Use a smaller image.
3. Center the block.
4. Add a caption.

In both tries the caption still shows aligned to the left in a narrow column: https://cld.wthms.co/hBO7MT
Test site: https://wpjcp20170718.wordpress.com/center-caption/

**Comment by torres126** [comment]
@laurelfulford I think they're related to the images used, I can reproduce the caption issue with some images but not others. From my testing, it seems to only be images which are transparent that cause the issue with the caption, such as [this one](https://backupclubpenguintorres126.files.wordpress.com/2018/11/music_jam_2010_access_login_screen_3.png). :)

**Comment by laurelfulford** [comment]
Thanks @jamiepalatnik! It was my bad -- it's not happening in Firefox, but once I switch to Chrome, I get it! :) Looking at a fix now!

**Comment by laurelfulford** [comment]
This should now be fully fixed, and committed in r51550-wpcom-themes! Thanks again for the extra deets, @jamiepalatnik!

**Comment by jamiepalatnik** [comment]
Awesome, seems to be working for me too. Thanks!

**Comment by torres126** [comment]
Automattic/wp-calypso/issues/28756
