### ISSUE TITLE
Alignments in post content not respected in block themes

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#5566]
## Steps to replicate

- Run Gutenberg trunk (after [this PR](https://github.com/WordPress/gutenberg/pull/38613) has been merged), activate a block theme that contains this [alignment CSS](https://github.com/Automattic/themes/blob/trunk/blockbase/sass/base/_alignment.scss#L35-L72) (Blockbase, TT2, Livro, Archeo...)
- Visit to the [alignments post](https://gist.github.com/MaggieCabrera/799d09c819616354a1b8eb3605f4fc69)
- Verify the alignments are not respected 

## Result

Post content does not correctly align wide or full:

![Screen Shot 2022-02-18 at 9 54 18 AM](https://user-images.githubusercontent.com/5375500/154736360-8a837877-dcfc-4e6f-9c26-70888b7c06f6.png)

## Next steps

We should [discuss the impact of the additional selectors](https://github.com/WordPress/gutenberg/pull/38613#discussion_r801431021) — if they are needed, or if we need to rework the alignments CSS.

**Comment by MaggieCabrera** [comment]
https://github.com/WordPress/gutenberg/pull/38947 should fix it

**Comment by jffng** [comment]
It did, thank you!

**Comment by iamtakashi** [comment]
I still see this issue in Site Editor. I've noticed it while I was playing with Livro that shows full content on the index. If this is better to be reported in https://github.com/WordPress/gutenberg/pull/38947, Let me know.

<img width="1680" alt="Screenshot 2022-02-23 at 12 24 00" src="https://user-images.githubusercontent.com/908665/155313033-49c9fc60-6d47-4edb-af51-9ef41b2ee32e.png">

**Comment by jffng** [comment]
Thanks @iamtakashi, looks like there is still an issue with the query / post template. A solution is being explored in https://github.com/WordPress/gutenberg/pull/39014#issuecomment-1049071340. 

We can re-open this for the time being.

**Comment by jffng** [comment]
We should verify this is fixed since https://github.com/WordPress/gutenberg/pull/39164 was merged.

**Comment by MaggieCabrera** [comment]
This looks ok to me, let's reopen if we find any alignments issues again.

Blockbase:

![Screenshot 2022-03-07 at 11-25-17 Alignments – Skatepark](https://user-images.githubusercontent.com/3593343/157013935-11ba8349-9ea9-45b5-bb3e-7f75b31fc592.jpg)

Livro:

![Screenshot 2022-03-07 at 11-26-56 Skatepark – Tagline](https://user-images.githubusercontent.com/3593343/157013958-4ad7e347-2499-4ff2-a331-4b924af9d74a.jpg)
