### ISSUE TITLE
Barnett: "Your theme needs to be updated before you can customize fonts"

### ISSUE THREAD

**Issue by villanovachile** [Automattic/themes#6154]
## Steps to replicate

When Barnett is activated, and trying to customize fonts in Appearance > Customize > Fonts, the following message is dispplayed: "Your theme needs to be updated before you can customize fonts"

• Issue occurs on both Simple & Atomic

## Result

![image](https://user-images.githubusercontent.com/65082164/176970935-269134a3-cfd3-44a1-b0d6-709d51974321.png)

## Expected

• I expected to be able to customize themes

* User report: 5342234-zen

**Comment by pbking** [comment]
This should be fixed by #6123 when it lands

**Comment by kalrus** [comment]
It looks like Gutenberg was updated today, July 6, but I am still seeing this issue on the Barnett theme.

**Comment by kathrynwp** [comment]
@pbking I noticed that https://github.com/Automattic/themes/pull/6123 is still open, could you please confirm when it will be merged on WordPress.com Simple/Atomic? 

Or if it has already been merged, could you please take another peek at this bug report? Thanks!

> It looks like Gutenberg was updated today, July 6, but I am still seeing this issue on the Barnett theme.

I'm not entirely clear on whether the PR referenced above is related to a Gutenberg update or not, but for the record, I still see this message on both Simple and Atomic sites, which both should be running Gutenberg 13.6.0 at the moment:

![Customize__Global_Styles_Demo_–_An_awesome_tagline](https://user-images.githubusercontent.com/7662449/177870733-db5b573a-2e0e-41b1-9bbb-ea9cce0a5168.jpg)
